<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ChatGPTv3.UI</RootNamespace>
    <AssemblyName>ChatGPTv3.UI</AssemblyName>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
	  <GenerateAmnManifest>false</GenerateAmnManifest>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <EnableDynamicLoading>true</EnableDynamicLoading>
	  <KeepOriginalFile>true</KeepOriginalFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Another-Mirai-Native.Abstractions" Version="1.2.4" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="5.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatGPTv3.Core\ChatGPTv3.Core.csproj" />
  </ItemGroup>

</Project>
