<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ChatGPTv3.Core</RootNamespace>
    <AssemblyName>ChatGPTv3.Core</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Another-Mirai-Native.Abstractions" Version="1.2.3" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.214" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatGPTv3.OpenAIClient\ChatGPTv3.OpenAIClient.csproj" />
  </ItemGroup>

</Project>
