using System.Text.Json;
using ChatGPTv3.Core.Api;
using ChatGPTv3.Core.Config;
using ChatGPTv3.Core.Utilities;
using ChatGPTv3.OpenAIClient;

namespace ChatGPTv3.Core.Model;

/// <summary>
/// Manages the bot's daily schedule, generated by LLM.
/// Cached to disk (schedules.json) and regenerated daily.
/// </summary>
public class SchedulerManager
{
    private const string Prompt = """
        我是{0}，{1}。请为我生成{2}（{3}）的日程安排，包括：
        1. 早上的学习或者工作或者娱乐安排
        2. 下午的活动和任务
        3. 晚上的计划和休息时间
        请按照时间顺序列出具体时间点和对应的活动，用一个时间点而不是时间段来表示时间，
        用JSON格式返回日程表，日程请关注细节并详细描述，涉及到游戏、动漫、节目或者书籍
        请明确作品名称，如果是游戏需要明确写出使用的角色以及自己的心情状态
        仅返回内容，不要返回注释，不要添加任何markdown或代码块样式，时间采用24小时制，
        格式为[{{"24小时制时间": "活动"}},{{"24小时制时间": "活动"}}]
        """;

    private Timer? _timer;
    private DateTime _lastUpdateTime;
    private List<(DateTime time, string action)> _schedules = [];
    private readonly string _cachePath = string.Empty;

    public static SchedulerManager? Instance { get; private set; }

    public SchedulerManager(string appDirectory)
    {
        Instance = this;
        _cachePath = Path.Combine(appDirectory, "schedules.json");
    }

    public void EnableTimer()
    {
        _timer = new Timer(_ => OnTimerTick(), null,
            TimeSpan.FromMinutes(1), TimeSpan.FromMinutes(1));
        Task.Run(UpdateScheduleAsync);
    }

    private void OnTimerTick()
    {
        if (AppConfig.EnableSchedules && DateTime.Now.Date != _lastUpdateTime.Date)
        {
            Task.Run(UpdateScheduleAsync);
        }
    }

    private async Task UpdateScheduleAsync()
    {
        // Try load from cache first
        if (_schedules.Count == 0 && File.Exists(_cachePath))
        {
            try
            {
                using var doc = JsonDocument.Parse(await File.ReadAllTextAsync(_cachePath));
                var lastUpdate = doc.RootElement.GetProperty("LastUpdateTime").GetDateTime();
                if (lastUpdate.Date == DateTime.Now.Date && doc.RootElement.TryGetProperty("Schedules", out var arr))
                {
                    _schedules = arr.EnumerateArray()
                        .Select(item => (
                            item.GetProperty("Time").GetDateTime(),
                            item.GetProperty("Action").GetString() ?? ""))
                        .ToList();
                    _lastUpdateTime = lastUpdate;
                    if (_schedules.Count > 0) return;
                }
            }
            catch { /* Cache invalid, regenerate */ }
        }

        // Generate via LLM
        var prompt = string.Format(Prompt,
            AppConfig.BotName, AppConfig.SchedulePrompt,
            DateTime.Now.ToLongDateString(), DateTime.Now.ToString("dddd"));

        var messages = new List<ChatMessage>
        {
            ChatMessage.System(prompt),
            ChatMessage.User("请回复")
        };

        try
        {
            var chatService = new ChatService();
            var json = await chatService.GetChatResultAsync(
                AppConfig.ChatAPIKeyId, messages,
                ChatService.Purpose.日程获取,
                timeout: AppConfig.ChatTimeout);

            if (json == ChatService.ErrorMessage) return;

            using var doc = JsonDocument.Parse(json);
            _schedules = doc.RootElement.EnumerateArray()
                .Select(item =>
                {
                    var prop = item.EnumerateObject().First();
                    return (DateTime.Parse(prop.Name), prop.Value.GetString() ?? "");
                })
                .ToList();

            _lastUpdateTime = DateTime.Now;
            CacheToFile();
        }
        catch (Exception ex)
        {
            CommonHelper.LogError?.Invoke("Schedule", ex.Message);
        }
    }

    private void CacheToFile()
    {
        var cache = new
        {
            LastUpdateTime = _lastUpdateTime,
            Schedules = _schedules.Select(s => new { Time = s.time, Action = s.action }).ToArray()
        };
        File.WriteAllText(_cachePath, cache.ToJson(true));
    }

    /// <summary>
    /// Updates or inserts a schedule entry at the given time.
    /// Called by the UpdateSchedule MCP tool.
    /// </summary>
    /// <param name="timeStr">Time string like "14:00" or "14:00:00".</param>
    /// <param name="newAction">New action description.</param>
    public void UpdateSchedule(string timeStr, string newAction)
    {
        if (!TimeSpan.TryParse(timeStr, out var ts)) return;

        var existing = _schedules.FindIndex(s => s.time.TimeOfDay == ts);
        if (existing >= 0)
            _schedules[existing] = (_schedules[existing].time.Date + ts, newAction);
        else
            _schedules.Add((DateTime.Today + ts, newAction));

        _schedules = _schedules.OrderBy(s => s.time.TimeOfDay).ToList();
        CacheToFile();
    }

    /// <summary>
    /// Gets the current schedule action for the given time.
    /// </summary>
    public string GetCurrentSchedule(DateTime time)
    {
        if (_schedules.Count <= 1) return AppConfig.DefaultSchedule;

        foreach (var (scheduleTime, action) in _schedules)
        {
            if (scheduleTime.TimeOfDay <= time.TimeOfDay)
            {
                // Check next schedule hasn't started yet
                var next = _schedules.FirstOrDefault(s => s.time.TimeOfDay > time.TimeOfDay);
                if (next == default || next.time.TimeOfDay > scheduleTime.TimeOfDay)
                    return action;
            }
        }

        return AppConfig.DefaultSchedule;
    }
}
